name: Update Site

on:
  workflow_dispatch: {}
  schedule:
  - cron:  "*/5 * * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      DIST_DIR: dist
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Update Site
      run: |
        bin/next_flights "${{ env.DIST_DIR }}/index.html"
      env:
        API_KEY: ${{ secrets.API_KEY }}
        API_SECRET: ${{ secrets.API_SECRET }}
        BASE_URL: ${{ vars.BASE_URL }}
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.DIST_DIR }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
